BT2H-4 Implement Temp Sensor and LCD screen
SWE-BoeingTech-2023-ECE/ECE pull request #3
Opened 2023-04-14 21:33 UTC by ammonson3

DESCRIPTION: added temp sensor and lcd screen to arduino code

TESTS: hardware tests

2023-04-16 17:33 UTC, ykalra requested changes
Apart from these small things, the code looks great! Thank you!

2023-04-16 17:33 UTC, ykalra commented on Hardware/Temp___Lcd.ino
> +char array1[]=" SunFounder               ";  //the string to print on the LCD
array1 and array 2 could be deleted as they are unused in the code

2023-04-16 17:33 UTC, ykalra commented on Hardware/Temp___Lcd.ino
> +int tim = 250;  //the value of delay time
tim could also be deleted, if unused

2023-04-23 18:33 UTC, riyabhat2002 approved these changes
Everything looks good! Thanks

2023-04-24 00:30 UTC, riyabhat2002 requested changes
I tried making this circuit and the temperature sensor works but it doesn't show anything on the LCD screen. Could you put up the circuit that you used initially in which the LCD screen showed the temperature?

2023-07-02 21:14 UTC, merged